### PR TITLE
Re-design examples repository for Effect

### PR DESCRIPTION
**Pull request by IMax153**
## Type

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This PR begins a redesign of the Effect `examples` repository with the following goals:

1. Contain the source code and publication infrastructure for a `create-effect-app` CLI which can be used to quickly setup an example Effect application
2. Contain a directory of example Effect applications similar to what [NextJS does in their own monorepo](https://github.com/vercel/next.js/tree/canary/examples)
3. The monorepo should be setup to, at the very least, type check both the examples and the CLI package via CI

### The CLI

The CLI is currently a scaffold / placeholder as I believe we have some open questions to answer first:

- Should the CLI be primarily prompt based similar to `create-next-app`?

My initial thoughts are that the CLI could be runnable like NextJS's, so:

```bash
pnpx create-effect-app [project-directory] 
```

And that the rest of the configuration could be obtained via prompts.

- Should we also include application templates alongside application examples like NextJS does?

My initial thoughts are that we should focus on examples for now and **not** include templates.

### The Examples

There are also some open questions for the design of the examples:

- How opinionated should we be with things like the package manager, linting config, etc.?

## Related

- Related Issue #
- Closes #

### CODE REVIEW

**Comment by tim-smart** [comment]
I would love a prompt based cli for scaffolding the following, in order of importance:

- A opinionated monorepo, because I hate setting up monorepos with all the right tooling
- A plain repo, with the right tooling
- A CLI project, with tsup ready to go

**Comment by mikearnaldi** [comment]
Re being opinionated we should be very opinionated having projects setup in the best way possible for effect usage. I agree with Tim I hate setting up stuff.

**Comment by fubhy** [comment]
Why do you want to put me out of work

**Comment by fubhy** [comment]
In addition to the project starterkits, I think the scaffolding tool should also be able to spin up projcets from the examples directly.

**Comment by fubhy** [comment]
Oh god, and please also a "minimal-repro" starter.

**Comment by mikearnaldi** [comment]
> Oh god, and please also a "minimal-repro" starter.

playground? but yes we could

**Comment by IMax153** [comment]
Merging this PR so that we can continue to iterate from here.

**Pull request merged**
